リポジトリの結果をレスポンスに詰める(固定値)
nakanakaShot/a-3181-core-punch-a-clock-api pull request #22
Opened 2020-04-17 08:32 UTC by k-narumi-mit

2020-04-17 08:40 UTC, nakanakaShot requested changes

2020-04-17 08:40 UTC, nakanakaShot commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/infrastructure/AttendRepository.java
> +    public final String ResponseMessage = "Hello_World!";
SNAKE_CASE でお願いします。

2020-04-17 08:40 UTC, nakanakaShot commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/presentation/AttendController.java
> +        return "Attend, starttime=" + now.format(timeFormat) + ", name=" + name + ", repository="
31行目でも `attendService.parameterBridge(name);` をしているようですがどうなっていますか？

2020-04-17 08:43 UTC, nakanakaShot requested changes

2020-04-17 08:43 UTC, nakanakaShot commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/presentation/AttendController.java
> +            + attendRepository.getParameter(name);
controller から infrastructureを呼び出すのはご法度です。

2020-04-17 08:50 UTC, nakanakaShot requested changes

2020-04-17 08:50 UTC, nakanakaShot commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/infrastructure/AttendRepository.java
> +    public final String ResponseMessage = "Hello_World!";
定数は static final で宣言してください。
外部に見せる必要がなければ可視性を private にしてください。

2020-04-18 04:54 UTC, nakanakaShot commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/infrastructure/AttendRepository.java
> +    public final String ResponseMessage = "Hello_World!";
ちなみにこの書き方は CamelCase といって、Javaでは クラスを定義する際に使用します

2020-04-18 04:54 UTC, nakanakaShot commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/presentation/AttendController.java
> +    private final AttendRepository attendRepository;
controller から infrastructureのrepositoryを呼び出すのはご法度です。

2020-04-20 01:49 UTC, mino213 reviewed
一点コメントしました

2020-04-20 01:49 UTC, mino213 commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/infrastructure/AttendRepository.java
> +    private static final String Response_Message = "Hello_World!";
定数名は全て大文字にして下さい

2020-04-20 02:14 UTC, nakanakaShot commented
リポジトリからの値がレスポンスに含まれるかどうかを、単体テストにて確認をお願いしたいです。

2020-04-20 02:20 UTC, k-narumi-mit commented on src/main/java/com/herokuapp/a3181core/punchaclockdev/infrastructure/AttendRepository.java
> +    private static final String Response_Message = "Hello_World!";
変更します

2020-04-20 04:07 UTC, nakanakaShot submitted a review, later dismissed
コメントはありません。蓑田さんのチェックを待ってください。

2020-04-20 07:12 UTC, mino213 approved these changes

2020-04-20 07:14 UTC, merged